name: x86-64 Pull and Save Docker Image
on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写docker镜像名称 多个用英文逗号分开'
        required: true
        default: 'homeassistant/home-assistant:latest,adguard/adguardhome:latest,lscr.io/linuxserver/jellyfin:latest'  # 设置默认的 Docker 镜像列表

jobs:
  pull_and_package:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        remove-android: 'true'
        remove-haskell: 'true'
        remove-dotnet: 'true'
        remove-visual-studio: 'true'
        overprovision-lvm: 'true'
      
    - name: Clean up Docker to free space
      run: |
          docker system prune -a -f
          docker volume prune -f

    - name: Pull Docker Images and Package
      run: |
        images="${{ github.event.inputs.docker_images }}"
          IFS=',' read -r -a image_array <<< "$images"
          for image in "${image_array[@]}"; do
            docker pull "${image}" --platform "linux/amd64"
            image_name="${image//\//_}"
            image_name="${image_name//:/_}"
            docker save "${image}" | gzip > "${image_name}-amd64.tar.gz"
            docker rmi "${image}"
          done

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: ${{ github.workspace }}/*.tar.gz
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天

    - name: Delete old assets inside Release （auto-build）, keep release/tag itself
      uses: georgezouq/delete-release-assets@v1
      if: success()
      with:
        tag_name: auto-build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload new tar.gz assets to same release
      uses: softprops/action-gh-release@v2
      if: success()
      with:
        files: |
          *.tar.gz
        tag_name: auto-build
        name: Auto Built docker images
        generate_release_notes:
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
