name: x86-64 Pull and Save Docker Image
on:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写docker镜像名称 多个用英文逗号分开'
        required: true
        default: 'homeassistant/home-assistant:latest,adguard/adguardhome:latest,lscr.io/linuxserver/jellyfin:latest'  # 设置默认的 Docker 镜像列表

jobs:
  pull_and_package:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      packages: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        remove-android: true
        remove-haskell: true
        remove-dotnet: true
        remove-codeql: true
        overprovision-lvm: true
      
    - name: Clean up Docker to free space
      run: |
          docker system prune -a -f
          docker volume prune -f

    - name: Pull Docker Images and Package
      run: |
        images="${{ github.event.inputs.docker_images }}"
        if [[ -z "$images" ]]; then
          images = 'homeassistant/home-assistant:latest,adguard/adguardhome:latest,lscr.io/linuxserver/jellyfin:latest'
        fi
          IFS=',' read -r -a image_array <<< "$images"
          for image in "${image_array[@]}"; do
            docker pull "${image}" --platform "linux/amd64"
            image_name="${image//\//_}"
            image_name="${image_name//:/_}"
            docker save "${image}" | gzip > "${image_name}-amd64.tar.gz"
            docker rmi "${image}"
          done

    - name: Debug print folder
      run: |
        pwd
        ls -la ./
        ls -la .//
        echo "images变量的值=【$images]"
        echo "数组长度: ${#image_array[@]}"
      
    - name: Upload to fix release tag(auto-build), overwrite same-name file
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create auto-build --draft --title "Latest Image Tarball" --notes "Auto-updated by workflow" -R ${{ github.repository }} || true 
        for tarfile in ./*-amd64.tar.gz; do
          gh release upload auto-build "$tarfile" --clobber -R ${{ github.repository }} 
        done
        if gh release view auto-build --json isDraft -R ${{ github.repository }} | jq -r '.isDraft' | grep -q true; then
          gh release edit auto-build --draft=false -R ${{ github.repository }} 
        fi
